### ISSUE TITLE
[BUG] bamm-cli 2.0.2 crashes on the approved and released CX model

### ISSUE THREAD

**Issue by jerzy-wachowiak** [OpenManufacturingPlatform/sds-sdk#198] opened 2022-08-05 07:45 UTC
**Describe the bug**
bamm-cli 2.0.1 crashes on the approved and released CX model https://github.com/catenax/BAMMmodels/tree/main/com.catenax.assembly_part_relationship/1.0.0 with the error: "Could not load Aspect io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Could not load Aspect model, please make sure the model is valid."
bamm-cli 1.0.2 works with the model without any problem...

**Where**
λ systeminfo
...
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
...
λ bamm2 --version
bamm-cli - BAMM Aspect Meta Model Command Line Tool
Version: 2.0.1
Build date: 2022-07-25T12:37:53Z
Git commit: f44105e11eb119f46132627547d527d548261c5e
λ java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

**Screenshots**
λ bamm2 aspect com.catenax.assembly_part_relationship/1.0.0/AssemblyPartRelationship.ttl validate
Warning: Nashorn engine is planned to be removed from a future JDK release
Validation report: Input model is valid

λ bamm2 aspect com.catenax.assembly_part_relationship/1.0.0/AssemblyPartRelationship.ttl to json
Could not load Aspect
io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Could not load Aspect model, please make sure the model is valid.
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.load(AspectModelLoader.java:80)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.lambda$fromVersionedModel$0(AspectModelLoader.java:113)
        at io.vavr.control.Try.flatMapTry(Try.java:490)
        at io.vavr.control.Try.flatMap(Try.java:472)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.fromVersionedModel(AspectModelLoader.java:97)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.fromVersionedModelUnchecked(AspectModelLoader.java:135)
        at io.openmanufacturing.sds.aspectmodel.generator.json.AspectModelJsonPayloadGenerator.<init>(AspectModelJsonPayloadGenerator.java:106)
        at io.openmanufacturing.sds.aspect.to.AspectToJsonCommand.run(AspectToJsonCommand.java:43)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.openmanufacturing.sds.BammCli.main(BammCli.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Type of example value on Property urn:bamm:com.catenax.assembly_part_relationship:1.0.0#quantity has incorrect type
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.lambda$apply$1(PropertyInstantiator.java:82)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.lambda$apply$3(PropertyInstantiator.java:80)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:79)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:39)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.lambda$getPropertiesModels$1(Instantiator.java:118)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getPropertiesModels(Instantiator.java:119)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.EntityInstantiator.apply(EntityInstantiator.java:41)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.EntityInstantiator.apply(EntityInstantiator.java:32)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getType(Instantiator.java:138)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.SetInstantiator.apply(SetInstantiator.java:40)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.SetInstantiator.apply(SetInstantiator.java:28)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:77)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:39)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.lambda$getPropertiesModels$1(Instantiator.java:118)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getPropertiesModels(Instantiator.java:119)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.AspectInstantiator.apply(AspectInstantiator.java:40)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.AspectInstantiator.apply(AspectInstantiator.java:32)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.load(AspectModelLoader.java:77)
        ... 24 common frames omitted
io.openmanufacturing.sds.metamodel.loader.AspectLoadingException: io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Could not load Aspect model, please make sure the model is valid.
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.lambda$fromVersionedModelUnchecked$2(AspectModelLoader.java:137)
        at io.vavr.control.Try.getOrElseThrow(Try.java:748)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.fromVersionedModelUnchecked(AspectModelLoader.java:135)
        at io.openmanufacturing.sds.aspectmodel.generator.json.AspectModelJsonPayloadGenerator.<init>(AspectModelJsonPayloadGenerator.java:106)
        at io.openmanufacturing.sds.aspect.to.AspectToJsonCommand.run(AspectToJsonCommand.java:43)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.openmanufacturing.sds.BammCli.main(BammCli.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Could not load Aspect model, please make sure the model is valid.
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.load(AspectModelLoader.java:80)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.lambda$fromVersionedModel$0(AspectModelLoader.java:113)
        at io.vavr.control.Try.flatMapTry(Try.java:490)
        at io.vavr.control.Try.flatMap(Try.java:472)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.fromVersionedModel(AspectModelLoader.java:97)
        ... 20 more
Caused by: io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Type of example value on Property urn:bamm:com.catenax.assembly_part_relationship:1.0.0#quantity has incorrect type
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.lambda$apply$1(PropertyInstantiator.java:82)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.lambda$apply$3(PropertyInstantiator.java:80)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:79)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:39)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.lambda$getPropertiesModels$1(Instantiator.java:118)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getPropertiesModels(Instantiator.java:119)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.EntityInstantiator.apply(EntityInstantiator.java:41)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.EntityInstantiator.apply(EntityInstantiator.java:32)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getType(Instantiator.java:138)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.SetInstantiator.apply(SetInstantiator.java:40)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.SetInstantiator.apply(SetInstantiator.java:28)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:77)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.PropertyInstantiator.apply(PropertyInstantiator.java:39)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.lambda$getPropertiesModels$1(Instantiator.java:118)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.openmanufacturing.sds.metamodel.loader.Instantiator.getPropertiesModels(Instantiator.java:119)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.AspectInstantiator.apply(AspectInstantiator.java:40)
        at io.openmanufacturing.sds.metamodel.loader.instantiator.AspectInstantiator.apply(AspectInstantiator.java:32)
        at io.openmanufacturing.sds.metamodel.loader.ModelElementFactory.create(ModelElementFactory.java:55)
        at io.openmanufacturing.sds.metamodel.loader.AspectModelLoader.load(AspectModelLoader.java:77)
        ... 24 more

**Additional context**
I would suggest to use CX models as tests. they present a broad variety of BAMM modelling approaches

**Comment by jerzy-wachowiak** [comment] 2022-08-05 08:02
Same behavior for bamm-cli-2.0.2.jar

**Comment by atextor** [comment] 2022-08-05 11:31
Hi @jerzy-wachowiak,
thank you for your report! The particular model (CatenaX Assembly Part Relationship) contains an invalid model construct which has actually been reported before, see #139.

There are actually three problems here:
1. The model is faulty - please see my comment in the issue linked above, which mentions what needs to be fixed
2. The formal meta model description is incomplete and does not correctly recognize the error. This leads to the false positive "model is valid". There is an issue to fix that: https://github.com/OpenManufacturingPlatform/sds-sdk/issues/199
3. The sds-sdk and bamm-cli use only the formal meta model description to validate a model, but do not try to load it. It could (and should) also try to load/parse the model in the same way the rest of the functions (such as "to json") do to prevent the false positive in the case the model contains indeed errors. There is also an issue for that now: https://github.com/OpenManufacturingPlatform/sds-sdk/issues/199
4. (optional) The error reporting of bamm-cli in case something still goes wrong could be improved

Since the root cause is in the model itself and the measures to address this in the meta model and the tooling are in the linked issues, I will close this issue.

**Closed by atextor** 2022-08-05 11:31 UTC
Labels: bug
