### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fmisir** [OpenManufacturingPlatform/sds-sdk#139] opened 2022-03-28 08:53 UTC
**Describe the bug**
The bamm cli fails to generate the html documentation for the following attached model:

[com.catenax.assembly_part_relationship.zip](https://github.com/OpenManufacturingPlatform/sds-sdk/files/8361140/com.catenax.assembly_part_relationship.zip)

The stack trace starts with: 

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'get' in  class java.util.Optional threw exception java.util.NoSuchElementException: No value present at /docu/templates/html/characteristic-documentation-lib.vm[line 277, column 32]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:308)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:235)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)
```

**Where**
**bamm cli version:** 1.0.2
**java version:**          OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

The error comes from the class 
`io.openmanufacturing.sds.aspectmodel.generator.docu.AspectModelDocumentationGenerator.lambda$generateHtmlDocu$1(AspectModelDocumentationGenerator.java:169)`

**Additional context**
The issue can be reproduced by executing:

1. download and unzip the attached Aspect Model
2. `cd` to the folder
3. execute `java -jar bamm-cli-1.0.2.jar -i AssemblyPartRelationship.ttl -html`

**Comment by atextor** [comment] 2022-04-01 07:04
Hello @fmisir,
I can reproduce the problem. When trying the documentation generation using [version 1.1.0-M3](https://github.com/OpenManufacturingPlatform/sds-sdk/releases/tag/v1.1.0-M3) of bamm-cli, the generation still fails, but the error messages are a little more helpful:

```
$ java -jar ~/bamm-cli-1.1.0-M3.jar -i AssemblyPartRelationship.ttl -html
Could not load Aspect
io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Could not load Aspect model, please make sure the model is valid.
[...snip...]
Caused by: io.openmanufacturing.sds.aspectmodel.resolver.exceptions.InvalidModelException: Type of example value on Property urn:bamm:com.catenax.assembly_part_relationship:1.0.0#quantity has incorrect type
```

In your provided Aspect Model, `:quantity`'s `bamm:exampleValue` is defined as follows:
```turtle
bamm:exampleValue "1 litre"^^:Quantity.
```

This declaration is wrong: The specification [states that](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-properties) `bamm:exampleValue`s may only be scalar., i.e., you currently can not provide an example value for a Property that has an Entity (like in this case, Quantity) as its effective type.
If it _were_ allowed, this would still be the wrong syntax, because the `^^` operator in RDF/Turtle attaches an XSD/RDF(S)-datatype to literals, and a string literal like "1 litre" can never be an instance of an Entity.

To fix it, remove wrong the example value from the model. Note that even then then generation with bamm-cli 1.0.2 will still fail due to a bug that is already fixed on main, but with 1.1.0-M3 it works.

If required, you could open a feature request for the [meta model](https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/issues) to allow non-scalar example values.

**Closed by atextor** 2022-04-01 07:04 UTC
Labels: bug
